default:
  theme_advanced_toolbar_align: left
  theme_advanced_buttons3_add:
    - tablecontrols
  plugins:
    - table

alternate:
  theme_advanced_toolbar_location: top
  theme_advanced_toolbar_align: left
  theme_advanced_buttons1 : "bold, italic, underline, numlist, bullist"
  theme_advanced_buttons2 : ""
  theme_advanced_buttons3 : ""
  plugins:
    - table